server.port: 8080
spring.datasource.url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
#options:
#collate: utf8mb4
#charset: utf8mb4
#type: InnoDB
spring.datasource.username: #????
spring.datasource.password: #????
spring.datasource.validation-interval: 50
spring.jpa.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto: update
spring.jpa.hibernate.globally_quoted_identifiers: create

indexing-settings:
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.playback.ru
      name: PlayBack.Ru
   # - url: https://www.skillbox.ru
    #  name: Skillbox

parse-settings:
  useragent: Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) YandexIndexingMach
bad-url:
  - url: https://www.svetlovka.ru
    name: svetlovka
  - url: https://dombulgakova.ru
    name: dombulgakova
  - url: https://ipfran.ru
    name: ipfran
  - url: https://fseconomy.net
    name: fseconomyHome
  - url: https://server.fseconomy.net
    name: fseconomyHomeServer
  - url: https://nikoartgallery.com
    name: nikoartgallery
