spring.datasource.url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&serverTimezone=UTC
spring.datasource.username: root
spring.datasource.password: jcnhjdtw22
spring.jpa.hibernate.ddl-auto: create

indexing-settings:
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru
   # - url: https://www.yandex.ru
   #   name: Yandex.Ru
